### ISSUE TITLE
Exchanging text data between Node and Python using async/await

### ISSUE THREAD

**Issue by ramseth001** [extrabacon/python-shell#262] opened 2022-01-18 07:59 UTC
Is it possible to exchanging text data between Node and Python using either callback function or async/await or promises instead of event emitters and listeners?

**Comment by Almenon** [comment] 2022-01-23 21:01
Duplicate of https://github.com/extrabacon/python-shell/issues/77

**Closed by Almenon** 2022-01-23 21:01 UTC
Labels: enhancement
